apiVersion: citacloud.buaa.edu.cn/v1
kind: ChainNode
metadata:
  name: chainnode-sample2
spec:
  # Add fields here
  configname: chainconfig-sample
  nodeid: "2" 
  network_key: MHg4OTU0M2IxMWUzMDliNzMzNTdhODhkYmQyNGFkNWU2YTM2ZjBjMjdhMzY1MTg5N2ZjNzlhNDk5MzgwZjdhYmRm 
