apiVersion: v1
kind: Service
metadata:
  name: buaa-chain-0
spec:
  ports:
  - port: 40000
    targetPort: 40000
    name: network
  - port: 22000
    targetPort: 22000
    name: syncthing
  - port: 8384
    targetPort: 8384
    name: gui
  selector:
    node_name: buaa-chain-0
---
apiVersion: v1
kind: Service
metadata:
  name: executor-buaa-chain-0
spec:
  type: NodePort
  ports:
  - port: 50002
    targetPort: 50002
    nodePort: 30009
    name: call
  selector:
    node_name: buaa-chain-0
---
apiVersion: v1
kind: Service
metadata:
  name: buaa-chain-1
spec:
  ports:
  - port: 40000
    targetPort: 40000
    name: network
  - port: 22000
    targetPort: 22000
    name: syncthing
  - port: 8384
    targetPort: 8384
    name: gui
  selector:
    node_name: buaa-chain-1
---
apiVersion: v1
kind: Service
metadata:
  name: executor-buaa-chain-1
spec:
  type: NodePort
  ports:
  - port: 50002
    targetPort: 50002
    nodePort: 30014
    name: call
  selector:
    node_name: buaa-chain-1
---
apiVersion: v1
kind: Service
metadata:
  name: buaa-chain-2
spec:
  ports:
  - port: 40000
    targetPort: 40000
    name: network
  - port: 22000
    targetPort: 22000
    name: syncthing
  - port: 8384
    targetPort: 8384
    name: gui
  selector:
    node_name: buaa-chain-2
---
apiVersion: v1
kind: Service
metadata:
  name: executor-buaa-chain-2
spec:
  type: NodePort
  ports:
  - port: 50002
    targetPort: 50002
    nodePort: 30019
    name: call
  selector:
    node_name: buaa-chain-2
---
apiVersion: v1
kind: Service
metadata:
  name: test-chain-node-port
spec:
  type: NodePort
  ports:
  - port: 50004
    targetPort: 50004
    nodePort: 30004
    name: rpc
  selector:
    chain_name: buaa-chain
