apiVersion: v1
kind: Service
metadata:
  name: chainnode-sample-0 #与network-config.toml对应
spec:
  ports:
  - port: 40000
    targetPort: 40000
    name: network
  - port: 22000
    targetPort: 22000
    name: syncthing
  - port: 8384
    targetPort: 8384
    name: gui
  selector:
    node_name: chainnode-sample-node-0 #与节点名字对应，下同
---
apiVersion: v1
kind: Service
metadata:
  name: executor-buaa-chain-0
spec:
  type: NodePort
  ports:
  - port: 50002
    targetPort: 50002
    nodePort: 30009
    name: call
  selector:
    node_name: chainnode-sample-node-0
---
apiVersion: v1
kind: Service
metadata:
  name: chainnode-sample-1
spec:
  ports:
  - port: 40000
    targetPort: 40000
    name: network
  - port: 22000
    targetPort: 22000
    name: syncthing
  - port: 8384
    targetPort: 8384
    name: gui
  selector:
    node_name: chainnode-sample-node-1
---
apiVersion: v1
kind: Service
metadata:
  name: executor-buaa-chain-1
spec:
  type: NodePort
  ports:
  - port: 50002
    targetPort: 50002
    nodePort: 30014
    name: call
  selector:
    node_name: chainnode-sample-node-1
---
apiVersion: v1
kind: Service
metadata:
  name: chainnode-sample-2
spec:
  ports:
  - port: 40000
    targetPort: 40000
    name: network
  - port: 22000
    targetPort: 22000
    name: syncthing
  - port: 8384
    targetPort: 8384
    name: gui
  selector:
    node_name: chainnode-sample-node-2
---
apiVersion: v1
kind: Service
metadata:
  name: executor-buaa-chain-2
spec:
  type: NodePort
  ports:
  - port: 50002
    targetPort: 50002
    nodePort: 30019
    name: call
  selector:
    node_name: chainnode-sample-node-2
---
apiVersion: v1
kind: Service
metadata:
  name: test-chain-node-port
spec:
  type: NodePort
  ports:
  - port: 50004
    targetPort: 50004
    nodePort: 30004
    name: rpc
  selector:
    chain_name: chainconfig-sample #与 chainconfig 的 name 对应
